version: "2"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"

  server:
    build: ./server/
    ports:
      - "6200:6200"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb